### ISSUE TITLE
Start in" Directory Not Set When Launching Apps from QuickPick

### ISSUE THREAD

**Issue by BoiHanny** [Ayazis/QuickPick#19]
Upon launching applications from QuickPick, I've noticed that the "Start in" directory is not being set. This has caused some issues with programs that attempt to access files in their "Start in" location. The absence of the correct directory path seems to hinder the functionality of such programs, as they are unable to locate necessary files to operate properly.

## Steps to Reproduce
1. Launch QuickPick.
2. Select and launch an application that requires access to specific files in its "Start in" directory.
3. Observe that the application is unable to locate the necessary files, indicating that the "Start in" directory path is not set correctly.

![image](https://github.com/Ayazis/QuickPick/assets/114599052/1a56e832-2149-4633-b780-199a4ddee364)

## Expected Behavior
The application should launch with the correct "Start in" directory path, allowing it to access the necessary files for proper functionality.

## Actual Behavior
The "Start in" directory path is not set, causing the application to fail in accessing the necessary files.

## Additional Information
- **QuickPick Version:** 1.0.4
- **Operating System:** Windows 11, build: 22621,2428

**Comment by Ayazis** [comment]
Thanks for reporting. This has slipped our attention. We will look into fixing it!

**Comment by Ayazis** [comment]
Has been fixed in version 1.0.5
