### ISSUE TITLE
The application's thumbnail appears to be offset

### ISSUE THREAD

**Issue by BoiHanny** [Ayazis/QuickPick#20]
The application's thumbnail appears to be offset within its bordered window (grid) when hovering over active apps.

## Steps to Reproduce
1. Hover over the active applications in the interface.
2. Observe the displayed thumbnail of the application.

## Expected Behavior
The application thumbnail should be centered within its bordered window (grid) with a title displayed above it.

![image](https://github.com/Ayazis/QuickPick/assets/114599052/ed5bd3cc-d0f8-4a4d-8ebf-522a70d07a20)
something like this?

## Actual Behavior
The application thumbnail is offset within the grid.

![image](https://github.com/Ayazis/QuickPick/assets/114599052/6fe4bcd8-0734-4112-ae90-cd329d544f73)

## Additional Information
- **QuickPick Version**: 1.0.4
- **Operating System**: Windows 11, build: 22621,2428

**Comment by Ayazis** [comment]
Thank you for reporting. This is Indeed a bug.

**Comment by Ayazis** [comment]
Has been fixed in version 1.0.5
