### ISSUE TITLE
Visual Selection Edge Artifact Appears When Activating QuickPick UI

### ISSUE THREAD

**Issue by BoiHanny** [Ayazis/QuickPick#26]
When using the QuickPick UI, a visual artifact resembling a selection edge, similar to when selecting icons on the desktop, sporadically appears around the screen edges.

**Steps to Reproduce:**
- Activate QuickPick with Ctrl + Right Click.
- Right-click again on the QuickPick wheel while it's still active.
- Observe the screen edges, especially after multiple right-clicks.
- Notice the visual selection edge artifact appearing intermittently.

**Expected Behavior:**
No visual artifacts should be present when activating and interacting with the QuickPick UI.

**Actual Behavior:**
An intermittent visual artifact appears around the screen edges upon activating and interacting with the QuickPick wheel.

**Additional Notes:**
The issue seems more pronounced with repeated right-click interactions on the QuickPick wheel once it's active.

Screenshots: 
![image](https://github.com/Ayazis/QuickPick/assets/114599052/361697e5-f927-4972-9a70-2f77c9237fa9)

**Comment by Ayazis** [comment]
This has been fixed :)
